cells:
  '0':
    label:
      dataRef: '0'
  '1':
    label:
      dataRef: '1'
  A:
    label:
      dataRef: A
  B:
    label:
      dataRef: B
  SrjY5U5Lp4LGjue5XJBE-10:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-10
  SrjY5U5Lp4LGjue5XJBE-7:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-7
  SrjY5U5Lp4LGjue5XJBE-8:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-8
  SrjY5U5Lp4LGjue5XJBE-9:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-9
  internet:
    label:
      dataRef: internet
  router:
    label:
      dataRef: router
  server1:
    label:
      dataRef: server1
  server2:
    label:
      dataRef: server2
  server3:
    label:
      dataRef: server3
