cells:
  '0':
    label:
      dataRef: '0'
  '1':
    label:
      dataRef: '1'
  server1:
    label:
      dataRef: server1
  server2:
    label:
      dataRef: server2
  server3:
    label:
      dataRef: server3
