cells:
  '0':
    label:
      dataRef: '0'
  '1':
    label:
      dataRef: '1'
  A:
    label:
      dataRef: A
  B:
    label:
      dataRef: B
  SrjY5U5Lp4LGjue5XJBE-1:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-1
  SrjY5U5Lp4LGjue5XJBE-10:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-10
  SrjY5U5Lp4LGjue5XJBE-2:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-2
  SrjY5U5Lp4LGjue5XJBE-3:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-3
  SrjY5U5Lp4LGjue5XJBE-5:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-5
  SrjY5U5Lp4LGjue5XJBE-6:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-6
  SrjY5U5Lp4LGjue5XJBE-7:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-7
  SrjY5U5Lp4LGjue5XJBE-8:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-8
  SrjY5U5Lp4LGjue5XJBE-9:
    label:
      dataRef: SrjY5U5Lp4LGjue5XJBE-9
